#ifndef CONFIG_H
#define CONFIG_H

#define MODULE_TYPE "cdplayer"

#define WEB_SERVER_CONCURRENT_CLIENTS_COUNT 3
#define WEB_SERVER_MESSAGE_MAX_LEN 2048

#define DEVICE_NAME_MAX_LEN 12

#define IR_LEARN_MODE_TIMEOUT_MS 30000
#define IR_LEARN_MODE_LOOP_INTERVAL_MS 250

#endif