#ifndef ENTITY_MEASUREMENT_VALIDATION_H
#define ENTITY_MEASUREMENT_VALIDATION_H

enum EntityMeasurementReadingErrors
{
    READING_TIMESPAN_NON_POSITIVE = 1,
    READING_TYPE_EMPTY = 2,
    READING_TYPE_TOO_LARGE = 3,
    READING_RAW_NOT_SET = 4,
    READING_ENTITY_NOT_FOUND = 5,
};

#endif