#ifndef MODULE_HARDWARE_H
#define MODULE_HARDWARE_H

#define DEBUG_ENABLED true
#define DEBUG_SERIAL_BAUDS 115200

#define WIFI_BUTTON_PIN 21
#define WIFI_BUTTON_LONG_PRESS_TRIGGER_MS 3000

#define SCHEDULER_RESOLUTION_MS 50
#define SCHEDULER_MAX_EVENTS 50

#define WEB_SERVER_PORT 80
#define WEB_SOCKET_PATH "/ws"
#define WEB_SOCKET_CLEANUP_CLIENTS_TASK_INTERVAL 1000

#define IR_RECEIVE_PIN 15
#define IR_SEND_PIN 4

#define COMMAND_HANDLER_KEY "handler"
#define COMMAND_REQUEST_ID_KEY "requestId"
#define COMMAND_CLIENT_ID_KEY "clientId"
#define COMMAND_RESPONSE_CODE_KEY "code"

#endif